#' Draw the intensity of the Markov-modulated Hawkes Process(MMHP)
#'
#' Take a mmhp object and draw its intensity accordingly
#'
#' @param mmhp a mmhp object including its state, state_time, tau, lambda0, lambda1, beta and alpha.
#' @param yupper upper limit of y axis of the plot.
#' @param add logical; if TRUE add to an already existing plot; if NA start a new plot taking the defaults for the limits and log-scaling of the x-axis from the previous plot. Taken as FALSE (with a warning if a different value is supplied) if no graphics device is open.
#' @param color A specification for the default plotting color.
#' @param given_main title of the plot.

#' @export
drawUniMMHPIntensity <- function (mmhp, yupper=10, add=FALSE, color = 1, given_main = "Intensity Plot of MMHP") {
  # input mmhp: mmhp object generated by mmhp.R
  t <- mmhp$tau
  state <- mmhp$state
  state_time <- mmhp$state_time
  lambda0 <- mmhp$lambda0
  lambda1 <- mmhp$lambda1
  alpha <- mmhp$alpha
  beta <- mmhp$beta

  n <- length(t)
  m <- length(state)

  if(add == FALSE){
    graphics::plot(0, 0, xlim = c(0, state_time[m]),ylim=c(0 ,yupper),type = "n",xlab = "Time",ylab = "Intensity",
         main = given_main)
    graphics::points(t[-1],rep(lambda0/2,n-1),cex = 0.6,pch = ifelse(mmhp$tau_state[-1] == 1, 16, 1),col = "blue")
    points(state_time,rep(lambda0,m),cex = 0.6,pch = 4,col = "red")
  }
  for(i in 1:(m-1)){
    if(state[i] == 1){
      hawkes_time <- t[t >= state_time[i] & t < state_time[i+1]]
      if(i == 1) hawkes_time <- hawkes_time[-1]
      history <- t[t < state_time[i]]
      drawHPIntensity(lambda1, i, alpha, beta, state_time[i], state_time[i + 1], history[-1], hawkes_time, color = color)
    }else{
      segments(x0 = state_time[i],x1 = state_time[i+1], y0 = lambda0, lty = 2,col = color)
    }
  }

  if(add == FALSE){
    graphics::legend("topleft", c("Hawkes event", "Poisson process event", "state change point"), col = c("blue", "blue", "red"),
           pch = c(16,1,4))
  }else{
    legend("topright", c("True","Estimation"), col = c("black", color), lty = c(1, 1))
  }
}
