---
title: "PPDiag"
output: pdf_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
devtools::load_all()  ## loads ppdiag
```

# Homogeneous Poisson Process

## Class
```{r}
pois_y <- hpp(lambda = 1, end = 10)

pois_y
```


## Simulate
```{r}
# events <- simulatehpp(lambda = 1, end = 10)
# events

pois_y$n <- 50
events <- simulatehpp(pois_y)
events
```

## Fit
```{r}

fithpp(events)

fit_hpp <- fithpp(events)

```

## Plot
```{r}
plothpp_step(events)
```


```{r}
drawHPPIntensity(pois_y,color = "red")

# this plots the fit_hpp intensity and its corresponding simulated events, since plot_events default is FALSE:
drawHPPIntensity(fit_hpp,events=events, color = "red")

# this plots the inputted events, since plot_events=TRUE:
drawHPPIntensity(fit_hpp, events=events, color = "red", plot_events=TRUE)
```

## Diagnostics
```{r}
diagpp(pois_y,t=events)
```

```{r}
intensityqqplot(fit_hpp,fit_hpp$start,fit_hpp$end,history=0,events=events)
```


# Hawkes Process

## Class
```{r}
hp_obj <- hp(lambda0 = 0.1,alpha = 0.45,beta = 0.5)
```

## Simulate
```{r}
# simulatehp(lambda0 = 0.1, alpha = 0.5, beta = 0.5, start = 0, end = 10,
#           history = 0)

sims <- simulatehp(hp_obj,start = 0, end = 100, history = 0)
sims

```

## Fit
```{r}
init=rep(0.1,3)

fithp(init,sims$t,max(sims$t))

fit_hp <- fithp(init,sims$t,max(sims$t))
```

## Plot
```{r}
# changing this to use hawkes event times

drawHPIntensity(hp_obj, start=0, end=max(sims$t), history=0, t=sims$t)

drawHPIntensity(fit_hp, start=0, end=max(sims$t), history=0, t=sims$t)

```

## Diagnostics
```{r}
diagpp(hp_obj, t=sims$t)
# this is the truth


diagpp(fit_hp, t = sims$t)

```

```{r}
intensityqqplot(fit_hp,start=0,end=max(events),history=0,events=events)
```


# MMHP
## Class
```{r}
Q <- matrix(c(-0.4, 0.4, 0.2, -0.2), ncol = 2, byrow = TRUE)

x <- mmhp(Q, delta = c(1 / 3, 2 / 3), 
          lambda0 = 0.2,
          lambda1 = .75,
          alpha = 0.1,
          beta = 0.2)
```

## Simulate
```{r}
y <- simulatemmhp(x,nsim = 5)
```

## Plot
```{r}
drawUniMMHPIntensity(x, y)
```

## Diagnostics
```{r}
try(diagpp(x, t=y))
try(intensityqqplot(object=x,min(y$tau),max(y$tau),history=0,events=y$tau,pzt=0.5))
```
