---
title: "Checking modified functions"
output:
  pdf_document: default
---
Date: 2020/6/15

This file shows tests of the modified functions drawHPIntensity, drawUniUniMMHPIntensity, and rawresidual. 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# check for rawresidual error message
```{R}
library(ppdiagrevised)
hp_object <- list(lambda0 = 0.03725967, alpha = 0.01374831, beta = 0.01968952)

class(hp_object) <- "p"

rawresidual(hp_object,t = events, termination = max(events))
```
This matches with the error message in pearsonresidual:
```{r}
pearsonresidual(hp_object,t = events, termination = max(events))
```

# check for drawUniMMHPIntensity
```{r}
library(SAPP)

data(Brastings)
events <- Brastings[301:length(Brastings)]
Q <- matrix(c(-0.4, 0.4, 0.2, -0.2), ncol = 2, byrow = TRUE) 
x <- mmhp(Q, delta = c(1 / 3, 2 / 3),
          lambda0 = 0.2,
          lambda1 = .75,
          alpha = 1.8,
          beta = 1.2)
y <- simulatemmhp(x,nsim = 10)
ppdiagrevised::drawUniMMHPIntensity(x, y)
```

# drawHPIntensity
```{r}
ppdiagrevised::drawHPIntensity(lambda0 = 0.03725967, alpha = 0.01374831, beta = 0.01968952,
start = min(events),
end = max(events), hawkes_time = events, history = Brastings[1:300],
i = 1)
```